pid_maze_solver:
  ros__parameters:
    waypoints_real: [0.925, 0.0, 0.0,   
                     0.83, 0.0, -1.5708,
                     0.0, -0.52, 0.0,
                     -0.372, 0.0, 0.0,
                     0.0, -0.532, 0.0,
                     0.375, 0.0, 0.0,
                     0.0, -0.535, 0.0,
                     -0.412, 0.0, 0.0,
                     -0.1, -0.325, -1.5708,
                     -0.385, 0.0, -1.5708,
                     0.0, 0.826, 1.5708,
                     -0.48, 0.05, -1.5708,
                     0.0, 0.51, 1.5708,
                     -0.33, 0.0, 3.1415]